name: Deploy to Minikube using GitHub Actions

on: [push]

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Start Minikube
      uses: medyagh/setup-minikube@master
      with:
        driver: docker
        
    - name: Build Docker image
      run: |
        eval $(minikube -p minikube docker-env)
        docker build -t devopshint/node-app:latest .
        
    - name: Deploy to Minikube
      run: kubectl apply -f k8s-node-app.yaml
      
    - name: Wait for Pod
      run: |
        kubectl wait --for=condition=ready pod -l app=nodejs-app --timeout=120s
        
    - name: Debug Pod Status
      run: |
        kubectl get pods -o wide
        kubectl describe pods
        kubectl get events
        
    - name: Test Service URL
      run: |
        echo "Waiting for service to be ready..."
        sleep 15
        URL=$(minikube service nodejs-app --url)
        echo "Service URL: $URL"
        curl --retry 5 --retry-delay 5 --connect-timeout 10 $URL | grep "Hello World"
        
    - name: Show Minikube Status
      run: |
        minikube status
        minikube service list
